// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd5d2Ieum-LeNyKfGcdSSiBwWtK6jXDNs',
    appId: '1:1076465008610:web:da53e04a38bfa17bc543bb',
    messagingSenderId: '1076465008610',
    projectId: 'ambu-book',
    authDomain: 'ambu-book.firebaseapp.com',
    storageBucket: 'ambu-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1p3xFyCSX-mZsYSwLVVKQE_ujuZL4ZeY',
    appId: '1:1076465008610:android:aabf7e9100f83f2fc543bb',
    messagingSenderId: '1076465008610',
    projectId: 'ambu-book',
    storageBucket: 'ambu-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJF5pq30oeHj2xI70Xpntt41TahUJOsp4',
    appId: '1:1076465008610:ios:a1823d6c9b4ff573c543bb',
    messagingSenderId: '1076465008610',
    projectId: 'ambu-book',
    storageBucket: 'ambu-book.appspot.com',
    iosClientId: '1076465008610-auf54vput2578mflb8drc2270aiev5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambubook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJF5pq30oeHj2xI70Xpntt41TahUJOsp4',
    appId: '1:1076465008610:ios:a1823d6c9b4ff573c543bb',
    messagingSenderId: '1076465008610',
    projectId: 'ambu-book',
    storageBucket: 'ambu-book.appspot.com',
    iosClientId: '1076465008610-auf54vput2578mflb8drc2270aiev5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambubook',
  );
}
